name: France
gdp: 24577800
health_resource_stockpile: 4812.0
sanitation_equipment_stockpile: 6341.0
human_welfare_resource: 1325.0
happiness_index: 0.75
procedure_resistance: 0.72
cleanliness_index: 0.595
disease_research_center: 0
vaccine_research_center: 0

vaccines_stock: 
  - name: ABC
    quantity: 20
    gdp_cost_per_step: 1000
    effectiveness: 0.4
  - name: ACB
    quantity: 30
    gdp_cost_per_step: 1000
    effectiveness: 0.22
  - name: BAC
    quantity: 10
    gdp_cost_per_step: 1000
    effectiveness: 0.95
  - name: BCA
    quantity: 12
    gdp_cost_per_step: 1000
    effectiveness: -0.2
  - name: CAB
    quantity: 23
    gdp_cost_per_step: 1000
    effectiveness: 0.5
  - name: CBA
    quantity: 10
    gdp_cost_per_step: 1000
    effectiveness: 0.1
loci:
  - name: Paris
    B: 0.0001
    C: 0.001
    E: 0.1
    A: 0.004
    Ds: 0.005
    Di: 0.009
    Dr: 0.0002
    lat: 48.8566
    lon: 2.3522
    susceptible: 2150000
    infected: 1000
    recovered: 100
    dead: 30
    area: 105.4
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Charles de Gaulle Airport
        zone_tier: 1
        infection_rate : 0.007
        effect: 1.0
      - name: Orly Airport
        zone_tier: 2
        infection_rate : 0.004
        effect: 1.0
    ports:
      - name: Port of Le Havre
        zone_tier: 1
        infection_rate : 0.0009
        effect: 1.0
    economic_zones:
      - name: La Défense
        zone_tier: 1
        effect: 1.0
      - name: Bercy
        zone_tier: 2
        effect: 1.0
      - name: Montmartre
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Eiffel Tower
        zone_tier: 1
        effect: 1.0
      - name: Louvre Museum
        zone_tier: 2
        effect: 1.0
      - name: Palace of Versailles
        zone_tier: 2
        effect: 1.0
  - name: Lyon
    B: 0.003
    C: 0.001
    E: 0.07
    A: 0.002
    Ds: 0.0004
    Di: 0.004
    Dr: 0.0001
    lat: 45.75
    lon: 4.85
    susceptible: 520000
    infected: 100
    recovered: 100
    dead: 30
    area: 47.87
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Lyon-Saint-Exupéry Airport
        zone_tier: 1
        infection_rate : 0.007
        effect: 1.0
      - name: Lyon-Bron Airport
        zone_tier: 2
        infection_rate : 0.0004
        effect: 1.0
    ports:
      - name: Port of Lyon
        zone_tier: 1
        infection_rate : 0.0004
        effect: 1.0
    economic_zones:
      - name: Part-Dieu
        zone_tier: 1
        effect: 1.0
      - name: Confluence
        zone_tier: 2
        effect: 1.0
      - name: Gerland
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Basilica of Notre-Dame de Fourvière
        zone_tier: 1
        effect: 1.0
      - name: Place Bellecour
        zone_tier: 2
        effect: 1.0
      - name: Parc de la Tête d'Or
        zone_tier: 2
        effect: 1.0
  - name: Marseille
    B: 0.03
    C: 0.004
    E: 0.05
    A: 0.02
    Ds: 0.0004
    Di: 0.004
    Dr: 0.0001
    lat: 43.2965
    lon: 5.3698
    susceptible: 870000
    infected: 100
    recovered: 100
    dead: 30
    area: 241
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Marseille Provence Airport
        zone_tier: 1
        infection_rate : 0.003
        effect: 1.0
      - name: Aix-en-Provence Airport
        zone_tier: 2
        infection_rate : 0.0004
        effect: 1.0
    ports:
      - name: Port of Marseille
        zone_tier: 1
        infection_rate : 0.0009
        effect: 1.0
      - name: Port of Toulon
        zone_tier: 1
        infection_rate : 0.0002
        effect: 1.0
    economic_zones:
      - name: Euroméditerranée
        zone_tier: 1
        effect: 1.0
      - name: La Joliette
        zone_tier: 2
        effect: 1.0
      - name: La Plaine
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Old Port of Marseille
        zone_tier: 1
        effect: 1.0
      - name: Calanques National Park
        zone_tier: 2
        effect: 1.0
      - name: Notre-Dame de la Garde
        zone_tier: 2
        effect: 1.0
  - name: Nice
    B: 0.005
    C: 0.004
    E: 0.1
    A: 0.06
    Ds: 0.0002
    Di: 0.007
    Dr: 0.0003
    lat: 43.7102
    lon: 7.262
    susceptible: 340000
    infected: 100
    recovered: 100
    dead: 30
    area: 71.92
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Nice Côte d'Azur Airport
        zone_tier: 1
        infection_rate : 0.003
        effect: 1.0
      - name: Cannes-Mandelieu Airport
        zone_tier: 2
        infection_rate : 0.002
        effect: 1.0
    ports:
      - name: Port of Nice
        zone_tier: 1
        infection_rate : 0.002
        effect: 1.0
      - name: Port of Cannes
        zone_tier: 1
        infection_rate : 0.002
        effect: 1.0
    economic_zones:
      - name: Nice Méridia
        zone_tier: 1
        effect: 1.0
      - name: Nice Acropolis
        zone_tier: 2
        effect: 1.0
      - name: Nice Arenas
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Promenade des Anglais
        zone_tier: 1
        effect: 1.0
      - name: Castle Hill
        zone_tier: 2
        effect: 1.0
      - name: Cours Saleya
        zone_tier: 2
        effect: 1.0